http://localhost:3000/players/


####
http://localhost:3000/players/5/

####
http://localhost:3000/players/5/
Content-Type: application/json

{
  "playerName": "Raju"
}

####
http://localhost:3000/players/5/matches

####
http://localhost:3000/matches/3/players

####
http://localhost:3000/players/3/playerScores/